### ISSUE TITLE
forcing output as webp or jpeg based on config

### ISSUE THREAD

**Issue by abhishekbuyt** [niiknow/docker-nginx-image-proxy#2]
i found your image filter module code to be the most appropriate for my cause. Trying to build on top of it and add the functionality of forcing output in a particular format. Having some issues with the code.

Would love support.

Thanks

**Comment by noogen** [comment]
It does png to jpeg right now if you pass in quality < 96, example:

https://nirklars.files.wordpress.com/2015/02/exomoon_of_binary_red_dwarfs__2_by_nirklars-d86asrr.png

http://imageproxy.niiknow.org/rx/q95/https://nirklars.files.wordpress.com/2015/02/exomoon_of_binary_red_dwarfs__2_by_nirklars-d86asrr.png


GIF is kind of tricky.  It's better to be JPEG if it's a photo; otherwise, GIF provide better compression.  "For a single photo frame, JPEG is a much better format both in quality and file size."  I would recommend using a service like cloundinary for anything else:  http://cloudinary.com/blog/animated_webp_how_to_convert_animated_gif_to_webp_and_save_up_to_90_bandwidth

Also, the problem, as you have face yourself, is that  this project is a hack of the original ngx_image_filter.  It's also using libdg which has it's own issues.  I would recommend doing anything more using ngx lua and magick/libvips.

**Comment by abhishekbuyt** [comment]
firstly, thanks for the response. 
In my use case i have to only deal with photos, and only relevant formats are png, jpeg and webp.
as webp still has limited support i want the request to be able to specify whether it wants a webp or a jpg of the image. While rendering it will force that type automatically.

Attaching my version of the imagefilter

[ngx_http_image_filter_module_jpeg_webp_flag.txt](https://github.com/niiknow/docker-nginx-image-proxy/files/1074439/ngx_http_image_filter_module_jpeg_webp_flag.txt)

you should be able to do a simple diff to see my changes.

** Issue i am facing currently is that when asking for a webp image the image is green instead of its natural color

**Comment by abhishekbuyt** [comment]
Just updating you. The code works fine. Was some issue in my libgd setup. On a proper set up it was returning the webp images as expected.
Still, Please look at the code i will submit a pull request if you want to add the functionality to your code.
Thanks.

**Comment by noogen** [comment]
Looks good, I was thinking something along the line of:
image_filter_output  string"jpg|jpeg|png|webp"

**Comment by noogen** [comment]
I have updated the code to support this feature.

Original: http://img08.deviantart.net/2c6f/i/2013/082/a/c/png_grass_by_moonglowlilly-d5z1o5t.png

Force Jpeg: http://imageproxy.niiknow.org/rx/200,ofmt_jpg/http://img08.deviantart.net/2c6f/i/2013/082/a/c/png_grass_by_moonglowlilly-d5z1o5t.png

Enjoy!

**Comment by noogen** [comment]
I added nginx directive _image_filter_output_

Update the server.conf to add output format/ofmt parameter.   This feature remove the old quality < 96 to force jpeg since it's no longer applicable.

**Comment by abhishekbuyt** [comment]
Thanks for the feature add :). I was half way through updating of the image_filter in a similar fashion.
