### ISSUE TITLE
404 resources serve 200 status code

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#21]
I think this should be handled better.

Now 404 resources return a 200 status code with empty gif. I think it should return a 404.

**Comment by noogen** [comment]
I initially do this to help things to just work; but you are right, I find that many sites rely on the error code and use image.onerror to load default image.   Of course, it wasn't really critical to have it on the default config because you should have your own server config.  But it provide a good example config so  I've made change in latest code.
