### ISSUE TITLE
Quality parameter doesn't affect certain images

### ISSUE THREAD

**Issue by demetriusnunes** [niiknow/docker-nginx-image-proxy#7]
These 2 urls result in the same exact image size and quality:

https://img.olxbr228.com/rx/372x278,q10/http://novaepoca.inforcedata.com.br/image/372862.jpg
https://img.olxbr228.com/rx/372x278,q100/http://novaepoca.inforcedata.com.br/image/372862.jpg

Although for these, it works correctly:
https://img.olxbr228.com/rx/372x278,q10/http://www.jtavares.com.br/fotos/2017/FI003895401.jpg
https://img.olxbr228.com/rx/372x278,q100/http://www.jtavares.com.br/fotos/2017/FI003895401.jpg

Any idea why?

**Comment by noogen** [comment]
Because, even though your image file extension is jpg, it's actually a png.  Try forcing output to jpg:  https://img.olxbr228.com/rx/372x278,q10,ofmt_jpeg/http://novaepoca.inforcedata.com.br/image/372862.jpg
https://img.olxbr228.com/rx/372x278,q100,ofmt_jpeg/http://novaepoca.inforcedata.com.br/image/372862.jpg

Even though quality can be set, it won't compress png.

**Comment by demetriusnunes** [comment]
Oh, awesome!! Thanks!
