### ISSUE TITLE
Add an option to have secure/signed URLs

### ISSUE THREAD

**Issue by demetriusnunes** [niiknow/docker-nginx-image-proxy#8]
For reference, see Thumbor security:
https://thumbor.readthedocs.io/en/latest/security.html

**Comment by noogen** [comment]
Security has not really been on my priority because we use a service called [StackPath](https://www.stackpath.com/) which provide DDoS, WAF protection, and caching.   We actually promote this image-proxy service to our users and encourage them to try out all the different parameters to simplify their setup.   Example, some users simply upload one big 2048x2048 image and use the service to provide different mobile home page icon sizes in the html head with rel="apple-touch-icon" or "icon" to support responsive website.

But since this is nginx, it's pretty simple to do with the built-in module:  

https://www.nginx.com/blog/securing-urls-secure-link-module-nginx-plus/

http://nginx.org/en/docs/http/ngx_http_secure_link_module.html?#secure_link_secret

Have you try out the configurations and maybe write a wiki/example config for anyone who want to implement it?

I would say, the higher priority would be:

1.  If this is a standalone service (not proxied behind some CDN) then limiting request per second per IP would be better.  https://www.nginx.com/blog/rate-limiting-nginx/

2.  Use openresty and lua instead of "if" statement in nginx conf to improve performance.   A lot of "if" in nginx can result in lower performance and ugly config.  Adding openresty can bring auto letsencrypt ssl to the table too: https://github.com/GUI/lua-resty-auto-ssl

BTW: the image was setup to allow user specific conf with SERVER_CONF environment variable

https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/root/bin/my-startup.sh#L18

Just create a URL of your conf somewhere and set it as the environment variable.  TIP: create a signed s3 secured URL if you want to secure your conf: http://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html

**Comment by demetriusnunes** [comment]
Thanks, I'll take a look at these references. Indeed, we're running the service behind a CDN and a load balancer so we might be able to use those to protect the service.
