### ISSUE TITLE
Won't resize image to bigger than original size

### ISSUE THREAD

**Issue by demetriusnunes** [niiknow/docker-nginx-image-proxy#9]
Any special reason for that?

This just creates an unexpected behavior since we don't usually know the original size of the image.

**Comment by noogen** [comment]
Unfortunately, the original library does not support upscale of image, "proportionally reduces an image to the specified sizes": http://nginx.org/en/docs/http/ngx_http_image_filter_module.html - original code here - https://github.com/nginx/nginx/blob/cac361718c741fd2bfe13d43aa2fabf23d0a2ca4/src/http/modules/ngx_http_headers_filter_module.c - that's why it is nginx native code

What you have are Features that various people modify/patched.  You're welcome to create pull request.  Maybe add a parameter called image_filter_upscale yes/no?  Segment the code to allow people to enable/disable this feature so it doesn't introduce instability into the lib.

**Comment by demetriusnunes** [comment]
Thanks! I can work around this limitation with CSS for now.
